### ISSUE TITLE
Plain JWT support

### ISSUE THREAD

**Issue by vokac** [scitokens/scitokens-cpp#110]
In the https://github.com/scitokens/scitokens-cpp/issues/53#issuecomment-876461070 it was mentioned plan to support "plain JWT", but it seems to me this did not yet happened, e.g. for all profiles except WLCG JWT `nbf` is still mandatory

https://github.com/scitokens/scitokens-cpp/blob/fc1ae5030c3865b965a38957ee87c485283577ad/src/scitokens_internal.h#L432-L436

so it is impossible to use HTCondor-CE with AARC tokens

```
02/06/23 00:41:10 (fd:17) (pid:773571) (D_AUDIT) Examining SciToken with payload {"exp":1675643497,"iat":1675639897,"auth_time":1657493020,"jti":"67b3ec77-980d-4eb0-a193-6f9a62cdb779","iss":"https://aai.egi.eu/auth/realms/egi","sub":"user@egi.eu","typ":"Bearer","azp":"oidc-agent","session_state":"cbde4873-2777-46f0-b61c-05a101f9aed3","scope":"openid eduperson_unique_id offline_access eduperson_scoped_affiliation eduperson_entitlement profile email","sid":"cbde4873-2777-46f0-b61c-
05a101f9aed3","authenticating_authority":"https://cern.ch/login"}.
02/06/23 00:41:10 (fd:17) (pid:773571) (D_SECURITY) SCITOKENS:2:Failed to deserialize scitoken: token verification failed: 'nbf' claim is mandatory
```

**Comment by djw8605** [comment]
I believe this has been fixed in #112
