### ISSUE TITLE
"Release" for version 1.1.0?

### ISSUE THREAD

**Issue by olifre** [scitokens/scitokens-cpp#133]
I see version 1.1.0 has been tagged and is already available in Fedora, but there is no GitHub release with artifacts yet (which is why I have missed this for example in packaging for Gentoo Linux). 

Could you please also add a release on GitHub for the new version? 
Many thanks in advance!

**Comment by djw8605** [comment]
Done!  Thanks

**Comment by olifre** [comment]
Thanks a lot for the quick release! Will take care of updating the packaging on Gentoo Linux later tonight :wink:.
