### ISSUE TITLE
storage.modify scope not honoured by scitokens-cpp

### ISSUE THREAD

**Issue by andreaceccanti** [scitokens/scitokens-cpp#27]
Hi,

while testing scope-based authz support in XRootD with @dciangot and @riccardodimaria we noticed that the scitokens library is not compliant with the WLCG profile. The storage.modify scope, in particular, is not honoured. Probably the cause of this is the following code:

https://github.com/scitokens/scitokens-cpp/blob/746a79c7020f10e011e00b8d896000e8bc11fc7e/src/scitokens_internal.cpp#L583

There's no "storage.write" scope in the WLCG profile.

And probably this shows up only in compatibility mode, which is however used by default IIUC.

**Comment by andreaceccanti** [comment]
Hi @bbockelm, can you comment on this?

**Comment by andreaceccanti** [comment]
@bbockelm  kind reminder.

**Comment by djw8605** [comment]
Hi,  We are looking into this with the change in #30 .  We are reviewing the change now.

**Comment by andreaceccanti** [comment]
Hi,
this is a blocker for the ESCAPE testbed. 
Is there any progress?

**Comment by djw8605** [comment]
You are right, storage.modify is not honored.  How would storage.modify be mapped to read/write?  Should it be considered a "write" authorization?

**Comment by andreaceccanti** [comment]
You can see the precise definition on what's expected from storage.modify here:

https://github.com/WLCG-AuthZ-WG/CommonJWTProfile/blob/master/profile.md#capability-based-authorization-scope

**Comment by djw8605** [comment]
Right, I read the definition the other day as well.  But I'm curious what the scitokens-cpp library should do?  The library primarily translates from the WLCG token profile to the SciTokens profile.  In this case, it would simply translate the storage.modify to write access.  Does that sound correct to you?  If that's the case, it should be a simple change to add storage.modify = (SciTokens) write.

**Comment by bbockelm** [comment]
@djw8605 - Xavi bumped me on this.

Indeed, I think we should just map WLCG's `storage.modify` -> `write` internally.  Can you do the change and crank a release?

**Comment by djw8605** [comment]
Ok, can do.  @andreaceccanti where do you get scitokens-cpp from?  EPEL or OSG?  EPEL has a bit of a delay due to testing and karma.

**Comment by riccardodimaria** [comment]
I personally get it from EPEL. Are you recommending to use OSG?

**Comment by djw8605** [comment]
Nope, EPEL is fine.  I'll push the update this morning and reply here when it is done.

**Comment by andreaceccanti** [comment]
@djw8605 Typically EPEL, but a fast track OSG repo will work fine for our testbed, thanks!

**Comment by djw8605** [comment]
The builds are now in testing for EPEL:
EL8: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-34e9284c7a
EL7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-805503deaa

Please leave positive karma if it works for you.

**Comment by dciangot** [comment]
Hi, I can confirm that now everything works as expected. Thanks!
