### ISSUE TITLE
ver attribute mismatch (scitoken != scitokens)

### ISSUE THREAD

**Issue by sfayer** [scitokens/scitokens-cpp#40]
Hi,

While doing some initial testing using version 0.5.1, I found that tokens from https://demo.scitokens.org could not be verified (using the scitokens-verify test program) with this error:
```
Failed to deserialize a token: token verification failed: Unknown profile version in token: scitoken:2.0
```

It appears that the code is expecting a version string of "scitokens:2.0" (with an "s"), but the demo.scitokens.org site and verification doc ( https://scitokens.org/technical_docs/Verification ) seem to indicate that the profile name should be "scitoken" (without an "s").

This seems to be a fairly fundamental problem, what am I missing here? Which of these profile names should I use in the tokens issued by my own OAuth2 server?

Regards,
Simon

**Comment by djw8605** [comment]
Yes, we identified this error not long ago, but didn't make the change yet.  I have now created a simple pull request in #41 that should solve this issue, while providing backward compatibility.  If you would like to review it, please do.

**Comment by sfayer** [comment]
Thanks for the quick response, looks good to me.
