### ISSUE TITLE
Lbrary and binary not installed if `-DBUILD_UNITTESTS=YES` is set

### ISSUE THREAD

**Issue by olifre** [scitokens/scitokens-cpp#82]
Packaging systems on Debian, Gentoo etc. run CMake once, configuring and then finally building the package. Afterwards, package tests are executed. If tests are successful, the package is installed. 

Since https://github.com/scitokens/scitokens-cpp/commit/b5855a714b600151a0c66fa9ab38c651e4c38efa , this does not work with `scitokens-cpp` anymore, which means tests can not be run in packaging (unless patching the `CMakeLists.txt`). 

Current Debian packaging has worked around this by not using `make install` of this package, but instead manually installing the binaries and library. For Gentoo, I am reverting the aforementioned patch. 

Could this patch be reverted upstream? This would allow getting rid of downstream workarounds.

**Comment by olifre** [comment]
For reference, here is the downstream patch:
https://github.com/gentoo/guru/commit/dac4048ba0ff88b2564a7ebfbbd29c267fd39a80

**Comment by olifre** [comment]
@DrDaveD I think I see the reason for the change now — it was to prevent the attempted installation of the internal `gtest`, correct? 
The PR I linked to this issue allows both: Installing the binaries if building the unit tests (and this allowing easy packaging in downstream distros), and not attempting to install the bundled `gtest`.

**Comment by olifre** [comment]
Fixed by #79 .

**Comment by DrDaveD** [comment]
I don't remember why exactly, but I believe it was to fix the CI failure on the previous commit.  The log of that failure isn't available so I can't see the details.  You could be right.
